import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.surveys': 'Surveys',
    'nav.needs': 'Needs',
    'nav.volunteers': 'Volunteers',
    'nav.map': 'Map',
    'nav.reports': 'Reports',
    'nav.availableTasks': 'Available Tasks',
    'nav.myTasks': 'My Tasks',
    'nav.profile': 'Profile',
    'nav.back': 'SevaLink',
    'nav.signIn': 'Sign In',
    'nav.joinVolunteer': 'Join as Volunteer',
    'nav.home': 'Home',
    'nav.settings': 'Settings',
    'nav.smartAssign': 'Smart Assign',
    'nav.logout': 'Sign Out',

    // Landing Page
    'landing.hero.title': 'Connecting Community Needs with the Right Help',
    'landing.hero.subtitle': 'Empowering NGOs and volunteers to create meaningful impact through smart data collection and coordination',
    'landing.cta.getStarted': 'Get Started',
    'landing.cta.joinVolunteer': 'Join as Volunteer',
    'landing.features.title': 'Powerful Features for Social Impact',
    'landing.features.subtitle': 'Everything you need to manage and coordinate community initiatives',
    'landing.how.title': 'How It Works',
    'landing.how.subtitle': 'Three simple steps to make a difference',
    'landing.impact.title': 'Our Impact',
    'landing.impact.subtitle': 'Making a difference, one community at a time',

    // Features
    'feature.data.title': 'Smart Data Collection',
    'feature.data.desc': 'OCR-powered survey extraction from paper forms and digital uploads',
    'feature.charts.title': 'Real-time Insights',
    'feature.charts.desc': 'Visualize community needs with interactive charts and analytics',
    'feature.vols.title': 'Volunteer Coordination',
    'feature.vols.desc': 'Match skilled volunteers with tasks they can make the biggest impact on',
    'feature.map.title': 'Geographic Mapping',
    'feature.map.desc': 'Track needs and resources across your community in real-time',

    // How It Works
    'how.step1.title': 'Collect Data',
    'how.step1.desc': 'Upload survey forms or use our OCR system to extract community needs from paper forms',
    'how.step2.title': 'Analyze Needs',
    'how.step2.desc': 'Our platform automatically categorizes and prioritizes needs based on urgency and location',
    'how.step3.title': 'Volunteers Take Action',
    'how.step3.desc': 'Skilled volunteers accept tasks and create real impact in their communities',

    // Impact
    'impact.people': 'People Helped',
    'impact.tasks': 'Tasks Completed',
    'impact.vols': 'Active Volunteers',
    'impact.communities': 'Communities Served',

    // Auth (Login & Signup)
    'auth.welcome': 'Welcome back',
    'auth.loginSubtitle': 'Sign in to continue making an impact',
    'auth.iam': 'I am a',
    'auth.admin': 'Admin',
    'auth.volunteer': 'Volunteer',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signInAs': 'Sign In as',
    'auth.signingIn': 'Signing in...',
    'auth.orContinue': 'Or continue with',
    'auth.googleSignIn': 'Sign in with Google',
    'auth.noAccount': "Don't have an account?",
    'auth.signup': 'Sign up',
    'auth.registration': 'Volunteer Registration',
    'auth.signupSubtitle': 'Join the community and make a difference.',
    'auth.fullName': 'Full Name',
    'auth.skills': 'Skills',
    'auth.location': 'Location',
    'auth.availability': 'Availability',
    'auth.language': 'Preferred Language',
    'auth.createAccount': 'Create Account',
    'auth.creatingAccount': 'Creating Account...',
    'auth.hasAccount': 'Already have an account?',
    'auth.loginHere': 'Sign in here',
    'auth.googleSignup': 'Sign up with Google',
    'auth.role.admin': 'NGO Admin',
    'auth.role.volunteer': 'Volunteer',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Track impact and manage community needs',
    'dashboard.stats.totalNeeds': 'Total Needs',
    'dashboard.stats.urgentTasks': 'Urgent Tasks',
    'dashboard.stats.activeVolunteers': 'Active Volunteers',
    'dashboard.stats.completedTasks': 'Completed Tasks',
    'dashboard.charts.needsArea': 'Needs by Area',
    'dashboard.charts.needsCategory': 'Needs by Category',
    'dashboard.charts.trends': 'Trends Over Time',
    'dashboard.activity.recent': 'Recent Activity',
    'dashboard.activity.empty': 'No recent activity. Run AI matchmaking to create assignments.',

    // Volunteer Dashboard
    'vol.stat.totalTasks': 'Total Tasks',
    'vol.stat.hours': 'Hours Contributed',
    'vol.stat.active': 'Active Tasks',
    'vol.stat.available': 'Available Hours',
    'vol.tasks.assigned': 'Assigned Tasks',
    'vol.tasks.empty': 'No tasks assigned yet',
    'vol.availability.title': 'Availability',
    'vol.achievements.title': 'Achievements',
    'vol.nextMilestone': 'Next Milestone',

    // Needs Page
    'needs.title': 'Community Needs',
    'needs.subtitle': 'Central coordination for all community aid requests and volunteer efforts',
    'needs.stat.unassigned': 'Unassigned',
    'needs.stat.assigned': 'Assigned',
    'needs.stat.critical': 'Critical',
    'needs.filter.search': 'Search by name, city, or ID...',
    'needs.filter.all': 'All Needs',
    'needs.filter.urgency': 'All Urgency',
    'needs.table.person': 'Person / ID',
    'needs.table.type': 'Type',
    'needs.table.urgency': 'Urgency',
    'needs.table.status': 'Status',
    'needs.table.assigned': 'Assigned To',
    'needs.table.actions': 'Actions',
    'needs.modal.edit': 'Edit Requirement',
    'needs.modal.firstName': 'First Name',
    'needs.modal.lastName': 'Last Name',
    'needs.modal.city': 'City / Area',
    'needs.modal.category': 'Requirement Category',
    'needs.modal.description': 'Description / Specifics',
    'needs.status.completed': 'Verified',
    'needs.status.pending': 'Pending Review',
    'needs.status.assigned': 'Assigned',
    'needs.status.inprogress': 'In Progress',
    'needs.status.data': 'Pending Data',
    'needs.toast.removeSuccess': 'Recipient removed successfully',
    'needs.toast.removeError': 'Failed to remove recipient',
    'needs.toast.verifySuccess': 'Action verified and closed',
    'needs.toast.verifyError': 'Failed to verify action',
    'needs.toast.updateSuccess': 'Recipient updated successfully',
    'needs.toast.updateError': 'Failed to update recipient',

    // Volunteers Page (Admin)
    'admin.vol.title': 'Volunteer Monitoring',
    'admin.vol.subtitle': 'Click any volunteer to view their full profile and performance',
    'admin.vol.stat.avgRating': 'Avg Rating',
    'admin.vol.filter.ratings': 'All Ratings',
    'admin.vol.filter.sort': 'Sort by',
    'admin.vol.filter.showInactive': 'Show Inactive',
    'admin.vol.performance': 'Performance',
    'admin.vol.stats.done': 'Tasks Done',
    'admin.vol.stats.active': 'Active Now',
    'admin.vol.stats.hours': 'Hours',
    'admin.vol.contact': 'Contact & Location',
    'admin.vol.skills': 'Core Skills',
    'admin.vol.rating': 'Performance Rating',
    'admin.vol.rating.outOf': 'out of 5.0',
    'admin.vol.membership': 'Membership',
    'admin.vol.memberSince': 'Date joined',
    'admin.vol.capabilities': 'Capabilities',
    'admin.vol.delivery': 'Delivery',
    'admin.vol.account': 'Account',
    'admin.vol.deactivate': 'Deactivate Volunteer',
    'admin.vol.reactivate': 'Reactivate Volunteer Account',
    'admin.vol.deactivateWarn': 'This will unassign all active cases and prevent new ones',
    'admin.vol.filter.rating4': '4.0 & Up',
    'admin.vol.filter.rating3': '3.0 & Up',
    'admin.vol.filter.ratingUnder3': 'Under 3.0',
    'admin.vol.filter.sortNewest': 'Newest',
    'admin.vol.filter.sortRatingHigh': 'Highest Rated',
    'admin.vol.filter.sortRatingLow': 'Lowest Rated',
    'admin.vol.filter.sortName': 'Name (A-Z)',
    'admin.vol.loading': 'Loading volunteer roster...',
    'admin.vol.more': 'more',
    'admin.vol.defaultLocation': 'Near Distribution Centre',
    'admin.vol.confirmDeactivate': 'Are you sure you want to deactivate this volunteer?',
    'admin.vol.confirmActivate': 'Are you sure you want to activate this volunteer?',
    'admin.vol.toastDeactivateSuccess': 'Volunteer deactivated successfully',
    'admin.vol.toastActivateSuccess': 'Volunteer activated successfully',
    'admin.vol.toastDeactivateError': 'Failed to deactivate volunteer',
    'admin.vol.toastActivateError': 'Failed to activate volunteer',
    'admin.vol.reactivateWarn': 'This will allow the volunteer to pick up cases again',
    'admin.vol.active': 'Active',
    'admin.vol.inactive': 'Inactive',

    // Map Legend & Categories
    'map.legend.high': 'High',
    'map.legend.medium': 'Medium',
    'map.legend.low': 'Low',
    'cat.food': 'Food',
    'cat.medical': 'Medical',
    'cat.shelter': 'Shelter',
    'cat.education': 'Education',
    'cat.other': 'Other',

    // Reports
    'reports.title': 'Impact Reports',
    'reports.subtitle': 'Measuring community aid and volunteer efficiency',
    'reports.export': 'Export CSV',
    'reports.ai.title': 'Generate AI Intelligence',
    'reports.ai.desc': 'Draft a semantic performance review using Gemini 1.5 Flash. Includes bottleneck analysis and regional demand forecasting.',
    'reports.ai.btn': 'Generate AI PDF',
    'reports.ai.loading': 'Analyzing...',
    'reports.stats.vols': 'Total Volunteers',
    'reports.stats.active': 'Active Field Units',
    'reports.stats.resolved': 'Needs Resolved',
    'reports.stats.rate': 'Resolution Rate',
    'reports.charts.trend': 'Fulfillment Trend Analysis',
    'reports.charts.priority': 'Priority Distribution',
    'reports.charts.geo': 'Geographical Impact Analysis',
    'reports.range.all': 'All Time',
    'reports.range.24h': 'Last 24 Hours',
    'reports.range.48h': 'Last 48 Hours',
    'reports.range.week': 'Last Week',
    'reports.range.month': 'Last Month',
    'reports.range.year': 'Last Year',

    // Smart Assign
    'smart.title': 'Smart Assign',
    'smart.subtitle': 'AI-powered mission control — from scattered data to immediate action',
    'smart.run': 'Run AI Matchmaker',
    'smart.running': 'Running AI Matchmaker...',
    'smart.priority': 'Priority Community Needs',
    'smart.complete': 'AI Matchmaking Complete!',
    'smart.how.title': 'How AI Assigns',
    'smart.how.step1.title': 'Reads All Needs',
    'smart.how.step1.desc': 'Pulls pending community needs ranked by urgency and area',
    'smart.how.step2.title': 'Profiles Volunteers',
    'smart.how.step2.desc': 'Analyses skills, location, rating & active load',
    'smart.how.step3.title': 'Semantic Matching',
    'smart.how.step3.desc': 'Gemini AI scores every possible volunteer-need pair',
    'smart.how.step4.title': 'Creates Actions',
    'smart.how.step4.desc': 'Generates assignments with a reason and match score',
    'smart.impact.title': 'Impact Snapshot',
    'smart.quick.title': 'Quick Actions',

    // Map View
    'map.title': 'Map Center',
    'map.filter.area': 'Filter Area',
    'map.filter.global': 'Global View',
    'map.filter.category': 'Category',
    'map.legend.title': 'Urgency Guide',
    'map.marker.volunteers': 'Volunteers',

    // Common
    'common.accept': 'Accept',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.details': 'Details',
    'common.loading': 'Loading...',
    'common.all': 'All',
  },
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.surveys': 'सर्वेक्षण',
    'nav.needs': 'आवश्यकताएं',
    'nav.volunteers': 'स्वयंसेवक',
    'nav.map': 'मानचित्र',
    'nav.reports': 'रिपोर्ट',
    'nav.availableTasks': 'उपलब्ध कार्य',
    'nav.myTasks': 'मेरे कार्य',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.back': 'सेवालिंक',
    'nav.signIn': 'साइन इन करें',
    'nav.joinVolunteer': 'स्वयंसेवक के रूप में शामिल हों',
    'nav.home': 'होम',
    'nav.settings': 'सेटिंग्स',
    'nav.smartAssign': 'स्मार्ट असाइन',
    'nav.logout': 'साइन आउट',

    // Landing Page
    'landing.hero.title': 'सामुदायिक आवश्यकताओं को सही मदद से जोड़ना',
    'landing.hero.subtitle': 'स्मार्ट डेटा संग्रह और समन्वय के माध्यम से सार्थक प्रभाव बनाने के लिए एनजीओ और स्वयंसेवकों को सशक्त बनाना',
    'landing.cta.getStarted': 'शुरू करें',
    'landing.cta.joinVolunteer': 'स्वयंसेवक के रूप में शामिल हों',
    'landing.features.title': 'सामाजिक प्रभाव के लिए शक्तिशाली विशेषताएं',
    'landing.features.subtitle': 'सामुदायिक पहलों के प्रबंधन और समन्वय के लिए आपको जो कुछ भी चाहिए',
    'landing.how.title': 'यह कैसे काम करता है',
    'landing.how.subtitle': 'बदलाव लाने के लिए तीन सरल कदम',
    'landing.impact.title': 'हमारा प्रभाव',
    'landing.impact.subtitle': 'एक समय में एक समुदाय, बदलाव लाना',

    // Features
    'feature.data.title': 'स्मार्ट डेटा संग्रह',
    'feature.data.desc': 'कागज के फॉर्म और डिजिटल अपलोड से ओसीआर-संचालित सर्वेक्षण निष्कर्षण',
    'feature.charts.title': 'रीयल-टाइम इनसाइट्स',
    'feature.charts.desc': 'इंटरैक्टिव चार्ट और एनालिटिक्स के साथ सामुदायिक आवश्यकताओं की कल्पना करें',
    'feature.vols.title': 'स्वयंसेवक समन्वय',
    'feature.vols.desc': 'कुशल स्वयंसेवकों को उन कार्यों के साथ मिलाएँ जिनका वे सबसे बड़ा प्रभाव डाल सकते हैं',
    'feature.map.title': 'भौगोलिक मानचित्रण',
    'feature.map.desc': 'वास्तविक समय में अपने समुदाय की जरूरतों और संसाधनों को ट्रैक करें',

    // How It Works
    'how.step1.title': 'डेटा एकत्र करें',
    'how.step1.desc': 'सर्वेक्षण फॉर्म अपलोड करें या कागज के फॉर्म से सामुदायिक जरूरतों को निकालने के लिए हमारे ओसीआर सिस्टम का उपयोग करें',
    'how.step2.title': 'आवश्यकताओं का विश्लेषण करें',
    'how.step2.desc': 'हमारा प्लेटफॉर्म तात्कालिकता और स्थान के आधार पर आवश्यकताओं को स्वचालित रूप से वर्गीकृत और प्राथमिकता देता है',
    'how.step3.title': 'स्वयंसेवक कार्रवाई करते हैं',
    'how.step3.desc': 'कुशल स्वयंसेवक कार्यों को स्वीकार करते हैं और अपने समुदायों में वास्तविक प्रभाव पैदा करते हैं',

    // Impact
    'impact.people': 'लोगों की मदद की',
    'impact.tasks': 'कार्य पूरे हुए',
    'impact.vols': 'सक्रिय स्वयंसेवक',
    'impact.communities': 'समुदायों की सेवा की',

    // Auth
    'auth.welcome': 'स्वागत है',
    'auth.loginSubtitle': 'प्रभाव जारी रखने के लिए साइन इन करें',
    'auth.iam': 'मैं हूँ',
    'auth.admin': 'प्रशासक',
    'auth.volunteer': 'स्वयंसेवक',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.signIn': 'साइन इन करें',
    'auth.signInAs': 'साइन इन करें के रूप में',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.orContinue': 'या इसके साथ जारी रखें',
    'auth.googleSignIn': 'गूगल के साथ साइन इन करें',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.signup': 'साइन अप करें',
    'auth.registration': 'स्वयंसेवक पंजीकरण',
    'auth.signupSubtitle': 'समुदाय में शामिल हों और बदलाव लाएं।',
    'auth.fullName': 'पूरा नाम',
    'auth.skills': 'कौशल',
    'auth.location': 'स्थान',
    'auth.availability': 'उपलब्धता',
    'auth.language': 'पसंदीदा भाषा',
    'auth.createAccount': 'खाता बनाएं',
    'auth.creatingAccount': 'खाता बन रहा है...',
    'auth.hasAccount': 'क्या पहले से कोई खाता है?',
    'auth.loginHere': 'यहाँ साइन इन करें',
    'auth.googleSignup': 'गूगल के साथ साइन अप करें',
    'auth.role.admin': 'एनजीओ प्रशासक',
    'auth.role.volunteer': 'स्वयंसेवक',

    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.subtitle': 'प्रभाव को ट्रैक करें और सामुदायिक आवश्यकताओं का प्रबंधन करें',
    'dashboard.stats.totalNeeds': 'कुल आवश्यकताएं',
    'dashboard.stats.urgentTasks': 'अति आवश्यक कार्य',
    'dashboard.stats.activeVolunteers': 'सक्रिय स्वयंसेवक',
    'dashboard.stats.completedTasks': 'पूरे किए गए कार्य',
    'dashboard.charts.needsArea': 'क्षेत्र के अनुसार आवश्यकताएं',
    'dashboard.charts.needsCategory': 'श्रेणी के अनुसार आवश्यकताएं',
    'dashboard.charts.trends': 'समय के साथ रुझान',
    'dashboard.activity.recent': 'हाल की गतिविधि',
    'dashboard.activity.empty': 'कोई हाल की गतिविधि नहीं। असाइनमेंट बनाने के लिए AI मैचमेकिंग चलाएं।',

    // Volunteer Dashboard
    'vol.stat.totalTasks': 'कुल कार्य',
    'vol.stat.hours': 'योगदान के घंटे',
    'vol.stat.active': 'सक्रिय कार्य',
    'vol.stat.available': 'उपलब्ध घंटे',
    'vol.tasks.assigned': 'असाइन किए गए कार्य',
    'vol.tasks.empty': 'अभी तक कोई कार्य असाइन नहीं किया गया है',
    'vol.availability.title': 'उपलब्धता',
    'vol.achievements.title': 'उपलब्धियां',
    'vol.nextMilestone': 'अगला मील का पत्थर',

    // Needs Page
    'needs.title': 'सामुदायिक आवश्यकताएं',
    'needs.subtitle': 'सभी सामुदायिक सहायता अनुरोधों और स्वयंसेवक प्रयासों के लिए केंद्रीय समन्वय',
    'needs.stat.unassigned': 'अनअसाइन किया गया',
    'needs.stat.assigned': 'असाइन किया गया',
    'needs.stat.critical': 'गंभीर',
    'needs.filter.search': 'नाम, शहर या आईडी से खोजें...',
    'needs.filter.all': 'सभी आवश्यकताएं',
    'needs.filter.urgency': 'सभी तात्कालिकता',
    'needs.table.person': 'व्यक्ति / आईडी',
    'needs.table.type': 'प्रकार',
    'needs.table.urgency': 'तात्कालिकता',
    'needs.table.status': 'स्थिति',
    'needs.table.assigned': 'किसे असाइन किया गया',
    'needs.table.actions': 'क्रियाएं',
    'needs.modal.edit': 'आवश्यकता संपादित करें',
    'needs.modal.firstName': 'पहला नाम',
    'needs.modal.lastName': 'अंतिम नाम',
    'needs.modal.city': 'शहर / क्षेत्र',
    'needs.modal.category': 'आवश्यकता श्रेणी',
    'needs.modal.description': 'विवरण / विवरण',
    'needs.status.completed': 'सत्यापित',
    'needs.status.pending': 'समीक्षा लंबित',
    'needs.status.assigned': 'असाइन किया गया',
    'needs.status.inprogress': 'प्रगति पर है',
    'needs.status.data': 'डेटा लंबित',
    'needs.toast.removeSuccess': 'प्राप्तकर्ता को सफलतापूर्वक हटा दिया गया',
    'needs.toast.removeError': 'प्राप्तकर्ता को हटाने में विफल',
    'needs.toast.verifySuccess': 'कार्रवाई सत्यापित और बंद कर दी गई',
    'needs.toast.verifyError': 'कार्रवाई सत्यापित करने में विफल',
    'needs.toast.updateSuccess': 'प्राप्तकर्ता को सफलतापूर्वक अपडेट कर दिया गया',
    'needs.toast.updateError': 'प्राप्तकर्ता को अपडेट करने में विफल',

    // Volunteers Page
    'admin.vol.title': 'स्वयंसेवक निगरानी',
    'admin.vol.subtitle': 'पूरा प्रोफाइल और प्रदर्शन देखने के लिए किसी भी स्वयंसेवक पर क्लिक करें',
    'admin.vol.stat.avgRating': 'औसत रेटिंग',
    'admin.vol.filter.ratings': 'सभी रेटिंग',
    'admin.vol.filter.sort': 'इसके अनुसार क्रमबद्ध करें',
    'admin.vol.filter.showInactive': 'निष्क्रिय दिखाएं',
    'admin.vol.performance': 'प्रदर्शन',
    'admin.vol.stats.done': 'कार्य पूरे हुए',
    'admin.vol.stats.active': 'अभी सक्रिय',
    'admin.vol.stats.hours': 'घंटे',
    'admin.vol.contact': 'संपर्क और स्थान',
    'admin.vol.skills': 'मुख्य कौशल',
    'admin.vol.rating': 'प्रदर्शन रेटिंग',
    'admin.vol.rating.outOf': '5.0 में से',
    'admin.vol.membership': 'सदस्यता',
    'admin.vol.memberSince': 'शामिल होने की तिथि',
    'admin.vol.capabilities': 'क्षमताएं',
    'admin.vol.delivery': 'वितरण',
    'admin.vol.account': 'खाता',
    'admin.vol.deactivate': 'स्वयंसेवक को निष्क्रिय करें',
    'admin.vol.reactivate': 'स्वयंसेवक खाता फिर से सक्रिय करें',
    'admin.vol.deactivateWarn': 'यह सभी सक्रिय मामलों को असाइन नहीं करेगा और नए मामलों को रोकेगा',
    'admin.vol.filter.rating4': '4.0 और ऊपर',
    'admin.vol.filter.rating3': '3.0 और ऊपर',
    'admin.vol.filter.ratingUnder3': '3.0 से कम',
    'admin.vol.filter.sortNewest': 'नवीनतम',
    'admin.vol.filter.sortRatingHigh': 'उच्चतम रेटिंग',
    'admin.vol.filter.sortRatingLow': 'सबसे कम रेटिंग',
    'admin.vol.filter.sortName': 'नाम (A-Z)',
    'admin.vol.loading': 'स्वयंसेवक सूची लोड हो रही है...',
    'admin.vol.more': 'और',
    'admin.vol.defaultLocation': 'वितरण केंद्र के पास',
    'admin.vol.confirmDeactivate': 'क्या आप वाकई इस स्वयंसेवक को निष्क्रिय करना चाहते हैं?',
    'admin.vol.confirmActivate': 'क्या आप वाकई इस स्वयंसेवक को सक्रिय करना चाहते हैं?',
    'admin.vol.toastDeactivateSuccess': 'स्वयंसेवक को सफलतापूर्वक निष्क्रिय कर दिया गया',
    'admin.vol.toastActivateSuccess': 'स्वयंसेवक को सफलतापूर्वक सक्रिय कर दिया गया',
    'admin.vol.toastDeactivateError': 'स्वयंसेवक को निष्क्रिय करने में विफल',
    'admin.vol.toastActivateError': 'स्वयंसेवक को सक्रिय करने में विफल',
    'admin.vol.reactivateWarn': 'यह स्वयंसेवक को फिर से मामले उठाने की अनुमति देगा',
    'admin.vol.active': 'सक्रिय',
    'admin.vol.inactive': 'निष्क्रिय',

    // Map Legend & Categories
    'map.legend.high': 'उच्च',
    'map.legend.medium': 'मध्यम',
    'map.legend.low': 'कम',
    'cat.food': 'भोजन',
    'cat.medical': 'चिकित्सा',
    'cat.shelter': 'आश्रय',
    'cat.education': 'शिक्षा',
    'cat.other': 'अन्य',

    // Reports
    'reports.title': 'प्रभाव रिपोर्ट',
    'reports.subtitle': 'सामुदायिक सहायता और स्वयंसेवक दक्षता को मापना',
    'reports.export': 'सीएसवी निर्यात करें',
    'reports.ai.title': 'एआई इंटेलिजेंस उत्पन्न करें',
    'reports.ai.desc': 'जेमिनी 1.5 फ्लैश का उपयोग करके एक सिमेंटिक प्रदर्शन समीक्षा ड्राफ्ट करें। इसमें बाधा विश्लेषण और क्षेत्रीय मांग पूर्वानुमान शामिल है।',
    'reports.ai.btn': 'एआई पीडीएफ उत्पन्न करें',
    'reports.ai.loading': 'विश्लेषण किया जा रहा है...',
    'reports.stats.vols': 'कुल स्वयंसेवक',
    'reports.stats.active': 'सक्रिय फील्ड इकाइयां',
    'reports.stats.resolved': 'आवश्यकताएं हल हुईं',
    'reports.stats.rate': 'समाधान दर',
    'reports.charts.trend': 'पूर्ति प्रवृत्ति विश्लेषण',
    'reports.charts.priority': 'प्राथमिकता वितरण',
    'reports.charts.geo': 'भौगोलिक प्रभाव विश्लेषण',
    'reports.range.all': 'पूरा समय',
    'reports.range.24h': 'पिछले 24 घंटे',
    'reports.range.48h': 'पिछले 48 घंटे',
    'reports.range.week': 'पिछला सप्ताह',
    'reports.range.month': 'पिछला महीना',
    'reports.range.year': 'पिछला वर्ष',

    // Smart Assign
    'smart.title': 'स्मार्ट असाइन',
    'smart.subtitle': 'एआई-संचालित मिशन कंट्रोल — बिखरे हुए डेटा से तत्काल कार्रवाई तक',
    'smart.run': 'एआई मैचमेकर चलाएं',
    'smart.running': 'एआई मैचमेकर चल रहा है...',
    'smart.priority': 'प्राथमिकता वाली सामुदायिक आवश्यकताएं',
    'smart.complete': 'एआई मैचमेकिंग पूरा हुआ!',
    'smart.how.title': 'एआई कैसे असाइन करता है',
    'smart.how.step1.title': 'सभी आवश्यकताओं को पढ़ता है',
    'smart.how.step1.desc': 'तात्कालिकता और क्षेत्र के आधार पर लंबित सामुदायिक आवश्यकताओं को प्राप्त करता है',
    'smart.how.step2.title': 'स्वयंसेवकों का प्रोफाइल बनाता है',
    'smart.how.step2.desc': 'कौशल, स्थान, रेटिंग और सक्रिय लोड का विश्लेषण करता है',
    'smart.how.step3.title': 'सिमेंटिक मिलान',
    'smart.how.step3.desc': 'जेमिनी एआई हर संभव स्वयंसेवक-आवश्यकता जोड़ी को स्कोर करता है',
    'smart.how.step4.title': 'कार्रवाई बनाता है',
    'smart.how.step4.desc': 'कारण और मिलान स्कोर के साथ असाइनमेंट उत्पन्न करता है',
    'smart.impact.title': 'प्रभाव स्नैपशॉट',
    'smart.quick.title': 'त्वरित कार्रवाई',

    // Map View
    'map.title': 'मानचित्र केंद्र',
    'map.filter.area': 'क्षेत्र फ़िल्टर करें',
    'map.filter.global': 'वैश्विक दृश्य',
    'map.filter.category': 'श्रेणी',
    'map.legend.title': 'तात्कालिकता निर्देशिका',
    'map.marker.volunteers': 'स्वयंसेवक',

    // Common
    'common.accept': 'स्वीकार करें',
    'common.submit': 'जमा करें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.details': 'विवरण',
    'common.loading': 'लोड हो रहा है...',
    'common.all': 'सभी',
  },
  mr: {
    // Navigation
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.surveys': 'सर्वेक्षण',
    'nav.needs': 'गरजा',
    'nav.volunteers': 'स्वयंसेवक',
    'nav.map': 'नकाशा',
    'nav.reports': 'अहवाल',
    'nav.availableTasks': 'उपलब्ध कार्ये',
    'nav.myTasks': 'माझी कार्ये',
    'nav.profile': 'प्रोफाइल',
    'nav.back': 'सेवालिंक',
    'nav.signIn': 'साइन इन करा',
    'nav.joinVolunteer': 'स्वयंसेवक म्हणून सामील व्हा',
    'nav.home': 'होम',
    'nav.settings': 'सेटिंग्ज',
    'nav.smartAssign': 'स्मार्ट असाइन',
    'nav.logout': 'साइन आउट',

    // Landing Page
    'landing.hero.title': 'समुदायाच्या गरजा योग्य मदतीशी जोडणे',
    'landing.hero.subtitle': 'स्मार्ट डेटा संकलन आणि समन्वयाद्वारे अर्थपूर्ण प्रभाव निर्माण करण्यासाठी एनजीओ आणि स्वयंसेवकांना सक्षम करणे',
    'landing.cta.getStarted': 'सुरू करा',
    'landing.cta.joinVolunteer': 'स्वयंसेवक म्हणून सामील व्हा',
    'landing.features.title': 'सामाजिक प्रभावासाठी शक्तिशाली वैशिष्ट्ये',
    'landing.features.subtitle': 'सामुदायिक उपक्रमांचे व्यवस्थापन आणि समन्वय साधण्यासाठी आपल्याला आवश्यक असलेले सर्व काही',
    'landing.how.title': 'हे कसे कार्य करते',
    'landing.how.subtitle': 'फरक करण्यासाठी तीन सोप्या पायऱ्या',
    'landing.impact.title': 'आमचा प्रभाव',
    'landing.impact.subtitle': 'एका वेळी एक समुदाय, फरक निर्माण करणे',

    // Features
    'feature.data.title': 'स्मार्ट डेटा संकलन',
    'feature.data.desc': 'कागदी फॉर्म आणि डिजिटल अपलोडमधून ओसीआर-आधारित सर्वेक्षण संकलन',
    'feature.charts.title': 'रिअल-टाइम आकडेवारी',
    'feature.charts.desc': 'परस्परसंवादी चार्ट आणि विश्लेषणासह समुदायाच्या गरजांचे दृश्यीकरण करा',
    'feature.vols.title': 'स्वयंसेवक समन्वय',
    'feature.vols.desc': 'कुशल स्वयंसेवकांना अशा कामांशी जोडा ज्यात ते सर्वात मोठा प्रभाव टाकू शकतात',
    'feature.map.title': 'भौगोलिक नकाशांकन',
    'feature.map.desc': 'रिअल-टाइममध्ये आपल्या समुदायातील गरजा आणि संसाधने ट्रॅक करा',

    // How It Works
    'how.step1.title': 'डेटा संकलित करा',
    'how.step1.desc': 'सर्वेक्षण फॉर्म अपलोड करा किंवा कागदी फॉर्ममधून समुदायाच्या गरजा काढण्यासाठी आमची ओसीआर प्रणाली वापरा',
    'how.step2.title': 'गरजांचे विश्लेषण करा',
    'how.step2.desc': 'आमचे प्लॅटफॉर्म तातडी आणि स्थानावर आधारित गरजा स्वयंचलितपणे वर्गीकृत आणि प्राधान्य देते',
    'how.step3.title': 'स्वयंसेवक कृती करतात',
    'how.step3.desc': 'कुशल स्वयंसेवक कामे स्वीकारतात आणि त्यांच्या समुदायांमध्ये खरा प्रभाव पाडतात',

    // Impact
    'impact.people': 'लोकांना मदत केली',
    'impact.tasks': 'कामे पूर्ण झाली',
    'impact.vols': 'सक्रिय स्वयंसेवक',
    'impact.communities': 'समुदायांची सेवा केली',

    // Auth
    'auth.welcome': 'पुन्हा स्वागत आहे',
    'auth.loginSubtitle': 'प्रभाव चालू ठेवण्यासाठी साइन इन करा',
    'auth.iam': 'मी आहे',
    'auth.admin': 'प्रशासक',
    'auth.volunteer': 'स्वयंसेवक',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.signIn': 'साइन इन करा',
    'auth.signInAs': 'साइन इन करा म्हणून',
    'auth.signingIn': 'साइन इन होत आहे...',
    'auth.orContinue': 'किंवा यासह सुरू ठेवा',
    'auth.googleSignIn': 'Google सह साइन इन करा',
    'auth.noAccount': 'खाते नाही?',
    'auth.signup': 'साइन अप करा',
    'auth.registration': 'स्वयंसेवक नोंदणी',
    'auth.signupSubtitle': 'समुदायात सामील व्हा आणि फरक करा.',
    'auth.fullName': 'पूर्ण नाव',
    'auth.skills': 'कौशल्ये',
    'auth.location': 'स्थान',
    'auth.availability': 'उपलब्धता',
    'auth.language': 'पसंतीची भाषा',
    'auth.createAccount': 'खाते तयार करा',
    'auth.creatingAccount': 'खाते तयार होत आहे...',
    'auth.hasAccount': 'आधीच खाते आहे का?',
    'auth.loginHere': 'येथे साइन इन करा',
    'auth.googleSignup': 'Google सह साइन अप करा',
    'auth.role.admin': 'एनजीओ प्रशासक',
    'auth.role.volunteer': 'स्वयंसेवक',

    // Dashboard
    'dashboard.title': 'डॅशबोर्ड',
    'dashboard.subtitle': 'प्रभाव ट्रॅक करा आणि समुदायाच्या गरजा व्यवस्थापित करा',
    'dashboard.stats.totalNeeds': 'एकूण गरजा',
    'dashboard.stats.urgentTasks': 'तातडीची कार्ये',
    'dashboard.stats.activeVolunteers': 'सक्रिय स्वयंसेवक',
    'dashboard.stats.completedTasks': 'पूर्ण झालेली कार्ये',
    'dashboard.charts.needsArea': 'क्षेत्रानुसार गरजा',
    'dashboard.charts.needsCategory': 'श्रेणीनुसार गरजा',
    'dashboard.charts.trends': 'वेळेनुसार कल',
    'dashboard.activity.recent': 'अलीकडील क्रियाकलाप',
    'dashboard.activity.empty': 'अलीकडील क्रियाकलाप नाही. असाइनमेंट तयार करण्यासाठी AI मॅचमेकिंग चालवा.',

    // Volunteer Dashboard
    'vol.stat.totalTasks': 'एकूण कार्ये',
    'vol.stat.hours': 'दिलेले तास',
    'vol.stat.active': 'सक्रिय कार्ये',
    'vol.stat.available': 'उपलब्ध तास',
    'vol.tasks.assigned': 'असाइन केलेली कार्ये',
    'vol.tasks.empty': 'अजून कोणतीही कार्ये असाइन केलेली नाहीत',
    'vol.availability.title': 'उपलब्धता',
    'vol.achievements.title': 'यश',
    'vol.nextMilestone': 'पुढील मैलाचा दगड',

    // Needs Page
    'needs.title': 'समुदायाच्या गरजा',
    'needs.subtitle': 'सर्व समुदायाच्या मदतीसाठी विनंत्या आणि स्वयंसेवक प्रयत्नांसाठी केंद्रीय समन्वय',
    'needs.stat.unassigned': 'असाइन न केलेले',
    'needs.stat.assigned': 'असाइन केलेले',
    'needs.stat.critical': 'गंभीर',
    'needs.filter.search': 'नाव, शहर किंवा आयडीने शोधा...',
    'needs.filter.all': 'सर्व गरजा',
    'needs.filter.urgency': 'सर्व तातडीकता',
    'needs.table.person': 'व्यक्ती / आयडी',
    'needs.table.type': 'प्रकार',
    'needs.table.urgency': 'तातडीकता',
    'needs.table.status': 'स्थिती',
    'needs.table.assigned': 'कोणाला सोपवले',
    'needs.table.actions': 'कृती',
    'needs.modal.edit': 'गरज संपादित करा',
    'needs.modal.firstName': 'पहिले नाव',
    'needs.modal.lastName': 'आडनाव',
    'needs.modal.city': 'शहर / परिसर',
    'needs.modal.category': 'गरज श्रेणी',
    'needs.modal.description': 'वर्णन / तपशील',
    'needs.status.completed': 'सत्यापित',
    'needs.status.pending': 'पुनरावलोकन प्रलंबित',
    'needs.status.assigned': 'असाइन केलेले',
    'needs.status.inprogress': 'प्रगतीपथावर',
    'needs.status.data': 'डेटा प्रलंबित',
    'needs.toast.removeSuccess': 'प्राप्तकर्ता यशस्वीरित्या काढून टाकला',
    'needs.toast.removeError': 'प्राप्तकर्ता काढण्यात अयशस्वी',
    'needs.toast.verifySuccess': 'कृती सत्यापित आणि बंद केली',
    'needs.toast.verifyError': 'कृती सत्यापित करण्यात अयशस्वी',
    'needs.toast.updateSuccess': 'प्राप्तकर्ता यशस्वीरित्या अपडेट केला',
    'needs.toast.updateError': 'प्राप्तकर्ता अपडेट करण्यात अयशस्वी',

    // Volunteers Page
    'admin.vol.title': 'स्वयंसेवक देखरेख',
    'admin.vol.subtitle': 'पूर्ण प्रोफाइल आणि कामगिरी पाहण्यासाठी कोणत्याही स्वयंसेवकावर क्लिक करा',
    'admin.vol.stat.avgRating': 'सरासरी रेटिंग',
    'admin.vol.filter.ratings': 'सर्व रेटिंग',
    'admin.vol.filter.sort': 'यानुसार क्रमवारी लावा',
    'admin.vol.filter.showInactive': 'निष्क्रिय दाखवा',
    'admin.vol.performance': 'कामगिरी',
    'admin.vol.stats.done': 'कामे पूर्ण झाली',
    'admin.vol.stats.active': 'आता सक्रिय',
    'admin.vol.stats.hours': 'तास',
    'admin.vol.contact': 'संपर्क आणि स्थान',
    'admin.vol.skills': 'मुख्य कौशल्ये',
    'admin.vol.rating': 'कामगिरी रेटिंग',
    'admin.vol.rating.outOf': '5.0 पैकी',
    'admin.vol.membership': 'सदस्यत्व',
    'admin.vol.memberSince': 'सामील झाल्याची तारीख',
    'admin.vol.capabilities': 'क्षमता',
    'admin.vol.delivery': 'वितरण',
    'admin.vol.account': 'खाते',
    'admin.vol.deactivate': 'स्वयंसेवक निष्क्रिय करा',
    'admin.vol.reactivate': 'स्वयंसेवक खाते पुन्हा सक्रिय करा',
    'admin.vol.deactivateWarn': 'हे सर्व सक्रिय केसेस काढून टाकेल आणि नवीन केसेस प्रतिबंधित करेल',
    'admin.vol.filter.rating4': '४.० आणि वर',
    'admin.vol.filter.rating3': '३.० आणि वर',
    'admin.vol.filter.ratingUnder3': '३.० च्या खाली',
    'admin.vol.filter.sortNewest': 'नवीनतम',
    'admin.vol.filter.sortRatingHigh': 'उच्चतम रेटिंग',
    'admin.vol.filter.sortRatingLow': 'सर्वात कमी रेटिंग',
    'admin.vol.filter.sortName': 'नाव (A-Z)',
    'admin.vol.loading': 'स्वयंसेवक यादी लोड होत आहे...',
    'admin.vol.more': 'आणखी',
    'admin.vol.defaultLocation': 'वितरण केंद्राजवळ',
    'admin.vol.confirmDeactivate': 'तुम्हाला खात्री आहे की तुम्ही हा स्वयंसेवक निष्क्रिय करू इच्छिता?',
    'admin.vol.confirmActivate': 'तुम्हाला खात्री आहे की तुम्ही हा स्वयंसेवक सक्रिय करू इच्छिता?',
    'admin.vol.toastDeactivateSuccess': 'स्वयंसेवक यशस्वीरित्या निष्क्रिय केला',
    'admin.vol.toastActivateSuccess': 'स्वयंसेवक यशस्वीरित्या सक्रिय केला',
    'admin.vol.toastDeactivateError': 'स्वयंसेवक निष्क्रिय करण्यात अयशस्वी',
    'admin.vol.toastActivateError': 'स्वयंसेवक सक्रिय करण्यात अयशस्वी',
    'admin.vol.reactivateWarn': 'हे स्वयंसेवकाला पुन्हा केसेस घेण्याची परवानगी देईल',
    'admin.vol.active': 'सक्रिय',
    'admin.vol.inactive': 'निष्क्रिय',

    // Map Legend & Categories
    'map.legend.high': 'उच्च',
    'map.legend.medium': 'मध्यम',
    'map.legend.low': 'कमी',
    'cat.food': 'अन्न',
    'cat.medical': 'वैद्यकीय',
    'cat.shelter': 'निवारा',
    'cat.education': 'शिक्षण',
    'cat.other': 'इतर',

    // Reports
    'reports.title': 'प्रभाव अहवाल',
    'reports.subtitle': 'समुदाय मदत आणि स्वयंसेवक कार्यक्षमतेचे मोजमाप',
    'reports.export': 'CSV निर्यात करा',
    'reports.ai.title': 'AI इंटेलिजन्स तयार करा',
    'reports.ai.desc': 'Gemini 1.5 Flash वापरून अर्थपूर्ण कामगिरी पुनरावलोकन तयार करा. यामध्ये अडथळा विश्लेषण आणि प्रादेशिक मागणी अंदाजाचा समावेश आहे.',
    'reports.ai.btn': 'AI PDF तयार करा',
    'reports.ai.loading': 'विश्लेषण होत आहे...',
    'reports.stats.vols': 'एकूण स्वयंसेवक',
    'reports.stats.active': 'सक्रिय फील्ड युनिट्स',
    'reports.stats.resolved': 'गरजा पूर्ण झाल्या',
    'reports.stats.rate': 'निराकरण दर',
    'reports.charts.trend': 'पूर्तता कल विश्लेषण',
    'reports.charts.priority': 'प्राधान्य वितरण',
    'reports.charts.geo': 'भौगोलिक प्रभाव विश्लेषण',
    'reports.range.all': 'सर्व वेळ',
    'reports.range.24h': 'मागील २४ तास',
    'reports.range.48h': 'मागील ४८ तास',
    'reports.range.week': 'मागील आठवडा',
    'reports.range.month': 'मागील महिना',
    'reports.range.year': 'मागील वर्ष',

    // Smart Assign
    'smart.title': 'स्मार्ट असाइन',
    'smart.subtitle': 'AI-सक्षम मिशन कंट्रोल — विखुरलेल्या डेटापासून त्वरित कारवाईपर्यंत',
    'smart.run': 'AI मॅचमेकर चालवा',
    'smart.running': 'AI मॅचमेकर चालत आहे...',
    'smart.priority': 'प्राधान्य सामुदायिक गरजा',
    'smart.complete': 'AI मॅचमेकिंग पूर्ण झाले!',
    'smart.how.title': 'AI कसे नियुक्त करते',
    'smart.how.step1.title': 'सर्व गरजा वाचते',
    'smart.how.step1.desc': 'तातडी आणि क्षेत्रानुसार प्रलंबित सामुदायिक गरजा खेचते',
    'smart.how.step2.title': 'स्वयंसेवकांची प्रोफाइल तपासते',
    'smart.how.step2.desc': 'कौशल्ये, स्थान, रेटिंग आणि सक्रिय भार यांचे विश्लेषण करते',
    'smart.how.step3.title': 'सिमेंटिक मॅचिंग',
    'smart.how.step3.desc': 'Gemini AI प्रत्येक शक्य स्वयंसेवक-गरज जोडीला गुण देते',
    'smart.how.step4.title': 'कृती तयार करते',
    'smart.how.step4.desc': 'कारण आणि मॅच स्कोअरसह असाइनमेंट तयार करते',
    'smart.impact.title': 'प्रभाव स्नॅपशॉट',
    'smart.quick.title': 'त्वरित कृती',

    // Map View
    'map.title': 'नकाशा केंद्र',
    'map.filter.area': 'क्षेत्र फिल्टर करा',
    'map.filter.global': 'जागतिक दृश्य',
    'map.filter.category': 'श्रेणी',
    'map.legend.title': 'तातडीकता मार्गदर्शिका',
    'map.marker.volunteers': 'स्वयंसेवक',

    // Common
    'common.accept': 'स्वीकारा',
    'common.submit': 'सबमिट करा',
    'common.cancel': 'रद्द करा',
    'common.save': 'जतन करा',
    'common.edit': 'संपादित करा',
    'common.delete': 'हटवा',
    'common.details': 'तपशील',
    'common.loading': 'लोड होत आहे...',
    'common.all': 'सर्व',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
